# User Defined
baseurl: "https://shmtuaa.org"
title: 上海海事大学算法协会
slogan: Shanghai Maritime University Association on Algorithm
description: SHMTU AA
paginate: 10
paginate_path: "page:num"
excerpt_separator:  "<!-- more -->"
websuffix: " - 上海海事大学算法协会"
lighttheme: "light"
darktheme: "dark"

# System Conf
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
sass:
  style: compressed

